2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_setup.py:_flush():67] Current SDK version is 0.19.9
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_setup.py:_flush():67] Configure stats pid to 72238
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_setup.py:_flush():67] Loading settings from /home/nickadkins47/.config/wandb/settings
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_setup.py:_flush():67] Loading settings from /home/nickadkins47/CS4900/CS4900-PA7/wandb/settings
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_init.py:setup_run_log_directory():662] Logging user logs to /home/nickadkins47/CS4900/CS4900-PA7/wandb/run-20250406_180814-rxw9r7jg/logs/debug.log
2025-04-06 18:08:14,151 INFO    MainThread:72238 [wandb_init.py:setup_run_log_directory():663] Logging internal logs to /home/nickadkins47/CS4900/CS4900-PA7/wandb/run-20250406_180814-rxw9r7jg/logs/debug-internal.log
2025-04-06 18:08:14,153 INFO    MainThread:72238 [wandb_init.py:init():781] calling init triggers
2025-04-06 18:08:14,154 INFO    MainThread:72238 [wandb_init.py:init():786] wandb.init called with sweep_config: {}
config: {'env_name': 'LunarLander-v3', 'policy_type': 'MlpPolicy', 'total_timesteps': 100000, '_wandb': {}}
2025-04-06 18:08:14,154 INFO    MainThread:72238 [wandb_init.py:init():809] starting backend
2025-04-06 18:08:14,154 INFO    MainThread:72238 [wandb_init.py:init():813] sending inform_init request
2025-04-06 18:08:14,158 INFO    MainThread:72238 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-04-06 18:08:14,158 INFO    MainThread:72238 [wandb_init.py:init():823] backend started and connected
2025-04-06 18:08:14,160 INFO    MainThread:72238 [wandb_init.py:init():915] updated telemetry
2025-04-06 18:08:14,171 INFO    MainThread:72238 [wandb_init.py:init():939] communicating run to backend with 90.0 second timeout
2025-04-06 18:08:14,666 INFO    MainThread:72238 [wandb_init.py:init():1014] starting run threads in backend
2025-04-06 18:08:14,743 INFO    MainThread:72238 [wandb_run.py:_console_start():2454] atexit reg
2025-04-06 18:08:14,744 INFO    MainThread:72238 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-04-06 18:08:14,744 INFO    MainThread:72238 [wandb_run.py:_redirect():2371] Wrapping output streams.
2025-04-06 18:08:14,744 INFO    MainThread:72238 [wandb_run.py:_redirect():2394] Redirects installed.
2025-04-06 18:08:14,745 INFO    MainThread:72238 [wandb_init.py:init():1056] run started, returning control to user process
2025-04-06 18:08:16,982 INFO    MainThread:72238 [wandb_run.py:_tensorboard_callback():1524] tensorboard callback: models/rxw9r7jg/log/PPO_1, True
2025-04-06 18:08:16,984 INFO    MainThread:72238 [wandb_watch.py:_watch():71] Watching
2025-04-06 18:08:16,985 INFO    MainThread:72238 [wandb_run.py:_config_callback():1327] config_cb None None {'algo': 'PPO', 'policy_class': "<class 'stable_baselines3.common.policies.ActorCriticPolicy'>", 'device': 'cpu', 'verbose': 1, 'policy_kwargs': '{}', 'num_timesteps': 0, '_total_timesteps': 100000, '_num_timesteps_at_start': 0, 'seed': 'None', 'action_noise': 'None', 'start_time': 1743977296971257635, 'learning_rate': 0.0003, 'tensorboard_log': 'models/rxw9r7jg/log', '_last_obs': '[[-0.00229769  1.4032342  -0.23274691 -0.34160116  0.00266924  0.05272055\n   0.          0.        ]]', '_last_episode_starts': '[ True]', '_last_original_obs': 'None', '_episode_num': 0, 'use_sde': 'False', 'sde_sample_freq': -1, '_current_progress_remaining': 1.0, '_stats_window_size': 100, 'ep_info_buffer': 'deque([], maxlen=100)', 'ep_success_buffer': 'deque([], maxlen=100)', '_n_updates': 0, '_custom_logger': 'False', 'env': '<stable_baselines3.common.vec_env.vec_video_recorder.VecVideoRecorder object at 0x7fb3b3fe6260>', '_vec_normalize_env': 'None', 'observation_space': 'Box([ -2.5        -2.5       -10.        -10.         -6.2831855 -10.\n  -0.         -0.       ], [ 2.5        2.5       10.        10.         6.2831855 10.\n  1.         1.       ], (8,), float32)', 'action_space': 'Discrete(4)', 'n_envs': 1, 'n_steps': 2048, 'gamma': 0.99, 'gae_lambda': 0.95, 'ent_coef': 0.0, 'vf_coef': 0.5, 'max_grad_norm': 0.5, 'rollout_buffer_class': "<class 'stable_baselines3.common.buffers.RolloutBuffer'>", 'rollout_buffer_kwargs': '{}', 'batch_size': 64, 'n_epochs': 10, 'clip_range': '<function get_schedule_fn.<locals>.<lambda> at 0x7fb36fa8c160>', 'clip_range_vf': 'None', 'normalize_advantage': 'True', 'target_kl': 'None', 'lr_schedule': '<function get_schedule_fn.<locals>.<lambda> at 0x7fb3b2c11870>', 'rollout_buffer': '<stable_baselines3.common.buffers.RolloutBuffer object at 0x7fb3b1a18070>', 'policy': 'ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor): FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor): MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=8, out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n      (0): Linear(in_features=8, out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n    )\n  )\n  (action_net): Linear(in_features=64, out_features=4, bias=True)\n  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)', '_logger': '<stable_baselines3.common.logger.Logger object at 0x7fb36fc48d00>'}
2025-04-06 18:10:15,917 INFO    MsgRouterThr:72238 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-04-06 18:10:16,082 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,200 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,303 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,406 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,509 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,613 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-04-06 18:10:16,718 ERROR   Thread-5  :72238 [redirect.py:_on_write():661] [no run ID] error in stdout callback
Traceback (most recent call last):
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 659, in _on_write
    cb(written_data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2375, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 387, in wrapper
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 435, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1518, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 761, in publish_output_raw
    self._publish_output_raw(o)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/home/nickadkins47/CS4900/CS4900-PA7/.venv/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
